### ISSUE TITLE
Commons module can not be found

### ISSUE THREAD

**Issue by badbob** [rabits/vk-backup#1]
Looks like some files was not commited into repository. 

```
$ python2.7 vk-backup.py --help
Traceback (most recent call last):
  File "vk-backup.py", line 14, in <module>
    from lib import Common as c
ImportError: cannot import name Common
```

**Comment by rabits** [comment]
Yeah, you're right - I forgot to add recursive to clone command into the readme. Common is a submodule in the lib directory: https://github.com/rabits/vk-backup/tree/master/lib
So you just need to clone it with --recursive:
```sh
git clone --recursive https://github.com/rabits/vk-backup.git
```

**Comment by rabits** [comment]
Seems like I missed that in the README.md I putted the right git clone command. So no fix required here.

**Comment by rabits** [comment]
Prepared release: https://github.com/rabits/vk-backup/releases/tag/0.8 - it contains the `tar.gz` archive with the latest code

**Comment by dmxt** [comment]
@rabits I still have same exact error, I tried cloning it and I also tried using your tar.gz. I still get 'No module named 'Common' error.

`python vk-backup.py --help`
```
Traceback (most recent call last):
  File "vk-backup.py", line 14, in <module>
    from lib import Common as c
  File "H:\Downloads\VK Photos Download\vk-backup\lib\Common\__init__.py", line 31, in <module>
    import Common as C
ImportError: No module named 'Common'
```

**Comment by rabits** [comment]
Hi @dmxt,

Seems like this issue is kinda different - I can see that Common submodule is here, but for some reason can't import `Common.py` from the `__init__.py`.

First of all I'd like to know what kind of python version you using. Could you please send some information about the environment?

**Comment by dmxt** [comment]
@rabits I apologize for late response, I did not get notified properly.

I'm using Windows 8 and Python 2.7 and I haven't run a python script before but I did run bash, npm, gulp, etc using [Cmder](http://cmder.net/) and sometimes [Babun](https://babun.github.io/). I believe that Python was fully functional where I was at since I was checking for Python version and it returned proper information in the cmd.

**Comment by rabits** [comment]
Prepared pretty the same environment, but found only issue #2 . Also tried path with spaces - seems like it's working well...
So I still think that you just don't have Common.py file in your `H:\Downloads\VK Photos Download\vk-backup\lib\Common` directory: just try to unpack tar archive again or clone recursive with git.
