### ISSUE TITLE
Сharmap сodec can't encode character

### ISSUE THREAD

**Issue by mrdimfox** [rabits/vk-backup#4]
I got this kind of error:
_ERROR, line:077 Exception: 'charmap' codec can't encode character u'\xec' in position 63: character maps to \<undefined\>_

Then the script is stopped.

Win 10,
Python 2.7.15, 
script flags: `--config-file=config.ini --verbose`,
**config.ini** file:
```
[VK-Backup]
user: ***
password: ***
backup-dir: backup
download-threads: 16
log-file: log.txt
```

**Comment by sparshev** [comment]
It's the first error in the output/log? Your config file encoding could be differ from UTF-8 and you using non-ascii symbols in your password - try to save it as UTF-8. Also please check your execution encoding, preferred to UTF-8.

**Comment by mrdimfox** [comment]
> It's the first error in the output/log?

Yes, it is. There were only warnings before such as
_Api responded error: One of the parameters specified was missing or invalid_

> Your config file encoding could be differ from UTF-8

It's not. It has UTF-8 encoding.

I get this error after about 30 minutes of script work.

> Also please check your execution encoding, preferred to UTF-8.

How can I check it?

**Comment by sparshev** [comment]
Ok, so seems env is using UTF-8 too. Need to see exception and not sure, that current version of vk-backup could provide it. So let me debug a little bit.

**Comment by rabits** [comment]
Will check it asap

**Comment by mrdimfox** [comment]
@rabits Cool, thx.

**Comment by rabits** [comment]
Ok, I found just one place where the error could happen - but could you please provide some prior logs, not just error itself.

**Comment by mrdimfox** [comment]
@rabits Ok. The script is finished successfully but only after I'd changed `download-threads` to **1** and started it from VS Code which use **PowerShell**, not **cmd** to start python scripts. Here is full log: [log.txt](https://gist.github.com/mrdimfox/64d57bb0935221a48a027d55cdc8d6d2)[deleted].

I can start the script from **cmd** again and copy full log to here. Upd: [here is it](https://gist.github.com/mrdimfox/f67277eafe170e6b4d5033ef8b9faa51)[deleted].

**Comment by rabits** [comment]
Ok, I saw what I need, but I asked only about couple of lines without all your private info))
Please remove the logs asap - they're containing private info like photos and friends id's.

**Comment by mrdimfox** [comment]
@rabits Oh sh~. Okay, I have deleted logs (:

**Comment by rabits** [comment]
Hi, just stopped by and found opened issue I forgot long time ago - so sorry(( So the issue you describing is with locale - just set `LC_ALL=UTF-8.en_US` and you should be good. Actually I'm working on updated version now, so probably will be not relevant...
